/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeforces;

import codeforces.practice.q4a;

public class App {
    public static void runq4a() {
        System.out.println(new q4a().solve(8));
    }

    public static void main(String[] args) {
        runq4a();
    }
}
